-- Database: BooksDB

-- DROP DATABASE IF EXISTS "BooksDB";

CREATE DATABASE "BooksDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'German_Germany.1252'
    LC_CTYPE = 'German_Germany.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Table: public.authors

-- DROP TABLE IF EXISTS public.authors;

CREATE TABLE IF NOT EXISTS public.authors
(
    authorid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    prename character varying(255),
    name character varying(255) NOT NULL,
    deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT authors_pkey PRIMARY KEY (authorid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.authors
    OWNER to postgres;

-- Table: public.books

-- DROP TABLE IF EXISTS public.books;

CREATE TABLE IF NOT EXISTS public.books
(
    bookid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    subtitle character varying(255),
    publishingdate character varying(50),
    format character varying(100),
    isbn13 character varying(13),
    isbn10 character varying(10),
    ispartofseries boolean NOT NULL DEFAULT false,
    deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT books_pkey PRIMARY KEY (bookid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.books
    OWNER to postgres;

-- Table: public.bookauthor

-- DROP TABLE IF EXISTS public.bookauthor;

CREATE TABLE IF NOT EXISTS public.bookauthor
(
    bookid integer NOT NULL,
    authorid integer NOT NULL,
    CONSTRAINT bookauthor_pkey PRIMARY KEY (bookid, authorid),
    CONSTRAINT bookauthor_authorid_fkey FOREIGN KEY (authorid)
        REFERENCES public.authors (authorid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bookauthor_bookid_fkey FOREIGN KEY (bookid)
        REFERENCES public.books (bookid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bookauthor
    OWNER to postgres;

-- Table: public.series

-- DROP TABLE IF EXISTS public.series;

CREATE TABLE IF NOT EXISTS public.series
(
    seriesid bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    CONSTRAINT series_pkey PRIMARY KEY (seriesid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.series
    OWNER to postgres;

-- Table: public.bookseries

-- DROP TABLE IF EXISTS public.bookseries;

CREATE TABLE IF NOT EXISTS public.bookseries
(
    bookid integer NOT NULL,
    seriesid integer NOT NULL,
    noinseries integer,
    CONSTRAINT bookseries_pk PRIMARY KEY (bookid, seriesid),
    CONSTRAINT bookseries_bookid_fk FOREIGN KEY (bookid)
        REFERENCES public.books (bookid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bookseries_seriesid_fk FOREIGN KEY (seriesid)
        REFERENCES public.series (seriesid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bookseries
    OWNER to postgres;

-- Table: public.lent

-- DROP TABLE IF EXISTS public.lent;

CREATE TABLE IF NOT EXISTS public.lent
(
    lentid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    bookid integer NOT NULL,
    prename character varying(255) NOT NULL,
    surname character varying(255),
    lentdate timestamp without time zone NOT NULL,
    active boolean DEFAULT true,
    CONSTRAINT lent_pkey PRIMARY KEY (lentid),
    CONSTRAINT lent_bookid_fkey FOREIGN KEY (bookid)
        REFERENCES public.books (bookid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.lent
    OWNER to postgres;

-- Table: public.settings

-- DROP TABLE IF EXISTS public.settings;

CREATE TABLE IF NOT EXISTS public.settings
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    topic character varying NOT NULL,
    setting character varying NOT NULL,
    inuse boolean,
    CONSTRAINT settings_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.settings
    OWNER to postgres;
-- Index: topicinuse

-- DROP INDEX IF EXISTS public.topicinuse;

CREATE UNIQUE INDEX IF NOT EXISTS topicinuse
    ON public.settings USING btree
    (topic COLLATE pg_catalog."default" ASC NULLS LAST, inuse ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: topicsetting

-- DROP INDEX IF EXISTS public.topicsetting;

CREATE UNIQUE INDEX IF NOT EXISTS topicsetting
    ON public.settings USING btree
    (topic COLLATE pg_catalog."default" ASC NULLS LAST, setting COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Table: public.settings_language

-- DROP TABLE IF EXISTS public.settings_language;

CREATE TABLE IF NOT EXISTS public.settings_language
(
    languageid integer NOT NULL,
    controlname character varying NOT NULL,
    text character varying,
    CONSTRAINT settings_language_pkey PRIMARY KEY (languageid, controlname),
    CONSTRAINT settings_language_languageid_fkey FOREIGN KEY (languageid)
        REFERENCES public.settings (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.settings_language
    OWNER to postgres;

-- FUNCTION: public.getalldates(integer, integer)

-- DROP FUNCTION IF EXISTS public.getalldates(integer, integer);

CREATE OR REPLACE FUNCTION public.getalldates(
	first integer,
	last integer)
    RETURNS TABLE(returnbookid integer) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
    RETURN QUERY
    SELECT BookID FROM Books WHERE RIGHT(PublishingDate, 4)::INT BETWEEN first AND last;
END
$BODY$;

ALTER FUNCTION public.getalldates(integer, integer)
    OWNER TO postgres;
